### ISSUE TITLE
Prosim premenujte repo na x[meno1]-x[meno2] nie IS ID, ospravedlnjem sa

### ISSUE THREAD

**Issue by fr6nco** [aks-2017/semestralne-zadania-semestralne-zadanie-xoravskym-xurbant#1]

**Comment by martinoravsky** [comment]
Nemame na to asi prava v classroome, hore nie je moznost Settings pre toto repo. Tebe to ide?

**Comment by fr6nco** [comment]
posli mi sem vase aisove loginy skusim to prepisat

**Comment by martinoravsky** [comment]
xoravskym, xurbant 

dik
